### PR TITLE
Added administration views

### PR DESCRIPTION
**Pull request by katafira**
<h1>Purpose</h1>
Created a new view for the administration menu. It is a tab where the admin will be able to see system info, and will have system lock and database control features.

@delaluzparra @alexvkcr @sergio-ocon 

Please be aware that this is part of a split of a previous big PR #24, therefore the old one will be closed as soon as the whole split is done and checked.

### CODE REVIEW

**Comment by katafira** [comment]
Ready to review.
@sergio-ocon @delaluzparra @alexvkcr 
<h4>Reminder: PR #38 inherits code from this one.</h4>

**Comment by sergio-ocon** [comment]
Great!

Can anyone review this?

**Comment by katafira** [comment]
@agarciavera @sebjimenez

**Comment by sergio-ocon** [comment]
I need a review on this. A LGTM is enough

**Comment by alexvkcr** [comment]
Looks good to me, tried locally

**Comment by alexvkcr** [comment]
Looks good to me, tried locally @sergio-ocon

**Pull request merged**
